<?php
declare(strict_types=1);

namespace Brotkrueml\Schema\Model\Type;

/*
 * This file is part of the "schema" extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

use Brotkrueml\Schema\Core\Model\AbstractType;

/**
 * A media object, such as an image, video, or audio object embedded in a web page or a downloadable dataset i.e. DataDownload. Note that a creative work may have many media objects associated with it on the same web page. For example, a page about a single song (MusicRecording) may have a music video (VideoObject), and a high and low bandwidth audio stream (2 AudioObject\&#039;s).
 */
final class MediaObject extends AbstractType
{
    protected $properties = [
        'about' => null,
        'accessMode' => null,
        'accessModeSufficient' => null,
        'accessibilityAPI' => null,
        'accessibilityControl' => null,
        'accessibilityFeature' => null,
        'accessibilityHazard' => null,
        'accessibilitySummary' => null,
        'accountablePerson' => null,
        'additionalType' => null,
        'aggregateRating' => null,
        'alternateName' => null,
        'alternativeHeadline' => null,
        'associatedArticle' => null,
        'associatedMedia' => null,
        'audience' => null,
        'audio' => null,
        'author' => null,
        'award' => null,
        'bitrate' => null,
        'character' => null,
        'citation' => null,
        'comment' => null,
        'commentCount' => null,
        'contentLocation' => null,
        'contentRating' => null,
        'contentSize' => null,
        'contentUrl' => null,
        'contributor' => null,
        'copyrightHolder' => null,
        'copyrightYear' => null,
        'creator' => null,
        'dateCreated' => null,
        'dateModified' => null,
        'datePublished' => null,
        'description' => null,
        'disambiguatingDescription' => null,
        'discussionUrl' => null,
        'duration' => null,
        'editor' => null,
        'educationalAlignment' => null,
        'educationalUse' => null,
        'embedUrl' => null,
        'encodesCreativeWork' => null,
        'encoding' => null,
        'encodingFormat' => null,
        'endTime' => null,
        'exampleOfWork' => null,
        'expires' => null,
        'funder' => null,
        'genre' => null,
        'hasPart' => null,
        'headline' => null,
        'height' => null,
        'identifier' => null,
        'image' => null,
        'inLanguage' => null,
        'interactionStatistic' => null,
        'interactivityType' => null,
        'isAccessibleForFree' => null,
        'isBasedOn' => null,
        'isFamilyFriendly' => null,
        'isPartOf' => null,
        'keywords' => null,
        'learningResourceType' => null,
        'license' => null,
        'locationCreated' => null,
        'mainEntity' => null,
        'mainEntityOfPage' => null,
        'material' => null,
        'mentions' => null,
        'name' => null,
        'offers' => null,
        'playerType' => null,
        'position' => null,
        'potentialAction' => null,
        'producer' => null,
        'productionCompany' => null,
        'provider' => null,
        'publication' => null,
        'publisher' => null,
        'publishingPrinciples' => null,
        'recordedAt' => null,
        'regionsAllowed' => null,
        'releasedEvent' => null,
        'requiresSubscription' => null,
        'review' => null,
        'sameAs' => null,
        'schemaVersion' => null,
        'sourceOrganization' => null,
        'spatial' => null,
        'spatialCoverage' => null,
        'sponsor' => null,
        'startTime' => null,
        'subjectOf' => null,
        'temporal' => null,
        'temporalCoverage' => null,
        'text' => null,
        'thumbnailUrl' => null,
        'timeRequired' => null,
        'translator' => null,
        'typicalAgeRange' => null,
        'uploadDate' => null,
        'url' => null,
        'version' => null,
        'video' => null,
        'width' => null,
        'workExample' => null,
    ];
}
