<?php

declare(strict_types=1);

/*
 * This file is part of the "schema" extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

namespace Brotkrueml\Schema\Model\Type;

use Brotkrueml\Schema\Attributes\Manual;
use Brotkrueml\Schema\Attributes\Type;
use Brotkrueml\Schema\Core\Model\AbstractType;
use Brotkrueml\Schema\Manual\Publisher;

/**
 * A software application designed specifically to work well on a mobile device such as a telephone.
 */
#[Type('MobileApplication')]
#[Manual(Publisher::Google, 'Software app', 'https://developers.google.com/search/docs/appearance/structured-data/software-app')]
#[Manual(Publisher::Yandex, 'Software', 'https://yandex.com/support/webmaster/supported-schemas/software.html')]
final class MobileApplication extends AbstractType
{
    protected static array $propertyNames = [
        'about',
        'abstract',
        'accessMode',
        'accessModeSufficient',
        'accessibilityAPI',
        'accessibilityControl',
        'accessibilityFeature',
        'accessibilityHazard',
        'accessibilitySummary',
        'accountablePerson',
        'acquireLicensePage',
        'additionalType',
        'aggregateRating',
        'alternateName',
        'alternativeHeadline',
        'applicationCategory',
        'applicationSubCategory',
        'applicationSuite',
        'archivedAt',
        'assesses',
        'associatedMedia',
        'audience',
        'audio',
        'author',
        'availableOnDevice',
        'award',
        'carrierRequirements',
        'character',
        'citation',
        'comment',
        'commentCount',
        'conditionsOfAccess',
        'contentLocation',
        'contentRating',
        'contentReferenceTime',
        'contributor',
        'copyrightHolder',
        'copyrightNotice',
        'copyrightYear',
        'correction',
        'countriesNotSupported',
        'countriesSupported',
        'countryOfOrigin',
        'creator',
        'creditText',
        'dateCreated',
        'dateModified',
        'datePublished',
        'description',
        'digitalSourceType',
        'disambiguatingDescription',
        'discussionUrl',
        'downloadUrl',
        'editEIDR',
        'editor',
        'educationalAlignment',
        'educationalUse',
        'encoding',
        'encodingFormat',
        'exampleOfWork',
        'expires',
        'featureList',
        'fileSize',
        'funder',
        'funding',
        'genre',
        'hasPart',
        'headline',
        'identifier',
        'image',
        'inLanguage',
        'installUrl',
        'interactionStatistic',
        'interactivityType',
        'interpretedAsClaim',
        'isAccessibleForFree',
        'isBasedOn',
        'isFamilyFriendly',
        'isPartOf',
        'keywords',
        'learningResourceType',
        'license',
        'locationCreated',
        'mainEntity',
        'mainEntityOfPage',
        'maintainer',
        'material',
        'materialExtent',
        'memoryRequirements',
        'mentions',
        'name',
        'offers',
        'operatingSystem',
        'owner',
        'pattern',
        'permissions',
        'position',
        'potentialAction',
        'processorRequirements',
        'producer',
        'provider',
        'publication',
        'publisher',
        'publishingPrinciples',
        'recordedAt',
        'releaseNotes',
        'releasedEvent',
        'review',
        'runtimePlatform',
        'sameAs',
        'schemaVersion',
        'screenshot',
        'sdDatePublished',
        'sdLicense',
        'sdPublisher',
        'size',
        'softwareAddOn',
        'softwareHelp',
        'softwareRequirements',
        'softwareVersion',
        'sourceOrganization',
        'spatial',
        'spatialCoverage',
        'sponsor',
        'storageRequirements',
        'subjectOf',
        'supportingData',
        'teaches',
        'temporal',
        'temporalCoverage',
        'text',
        'thumbnail',
        'thumbnailUrl',
        'timeRequired',
        'translator',
        'typicalAgeRange',
        'url',
        'usageInfo',
        'version',
        'video',
        'wordCount',
        'workExample',
    ];
}
