<?php
declare(strict_types=1);

namespace Brotkrueml\Schema\Model\Type;

/*
 * This file is part of the "schema" extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

use Brotkrueml\Schema\Core\Model\AbstractType;

/**
 * Web applications.
 */
final class WebApplication extends AbstractType
{
    protected $properties = [
        'about' => null,
        'accessMode' => null,
        'accessModeSufficient' => null,
        'accessibilityAPI' => null,
        'accessibilityControl' => null,
        'accessibilityFeature' => null,
        'accessibilityHazard' => null,
        'accessibilitySummary' => null,
        'accountablePerson' => null,
        'additionalType' => null,
        'aggregateRating' => null,
        'alternateName' => null,
        'alternativeHeadline' => null,
        'applicationCategory' => null,
        'applicationSubCategory' => null,
        'applicationSuite' => null,
        'associatedMedia' => null,
        'audience' => null,
        'audio' => null,
        'author' => null,
        'availableOnDevice' => null,
        'award' => null,
        'browserRequirements' => null,
        'character' => null,
        'citation' => null,
        'comment' => null,
        'commentCount' => null,
        'contentLocation' => null,
        'contentRating' => null,
        'contributor' => null,
        'copyrightHolder' => null,
        'copyrightYear' => null,
        'countriesNotSupported' => null,
        'countriesSupported' => null,
        'creator' => null,
        'dateCreated' => null,
        'dateModified' => null,
        'datePublished' => null,
        'description' => null,
        'disambiguatingDescription' => null,
        'discussionUrl' => null,
        'downloadUrl' => null,
        'editor' => null,
        'educationalAlignment' => null,
        'educationalUse' => null,
        'encoding' => null,
        'encodingFormat' => null,
        'exampleOfWork' => null,
        'expires' => null,
        'featureList' => null,
        'fileSize' => null,
        'funder' => null,
        'genre' => null,
        'hasPart' => null,
        'headline' => null,
        'identifier' => null,
        'image' => null,
        'inLanguage' => null,
        'installUrl' => null,
        'interactionStatistic' => null,
        'interactivityType' => null,
        'isAccessibleForFree' => null,
        'isBasedOn' => null,
        'isFamilyFriendly' => null,
        'isPartOf' => null,
        'keywords' => null,
        'learningResourceType' => null,
        'license' => null,
        'locationCreated' => null,
        'mainEntity' => null,
        'mainEntityOfPage' => null,
        'material' => null,
        'memoryRequirements' => null,
        'mentions' => null,
        'name' => null,
        'offers' => null,
        'operatingSystem' => null,
        'permissions' => null,
        'position' => null,
        'potentialAction' => null,
        'processorRequirements' => null,
        'producer' => null,
        'provider' => null,
        'publication' => null,
        'publisher' => null,
        'publishingPrinciples' => null,
        'recordedAt' => null,
        'releaseNotes' => null,
        'releasedEvent' => null,
        'review' => null,
        'sameAs' => null,
        'schemaVersion' => null,
        'screenshot' => null,
        'softwareAddOn' => null,
        'softwareHelp' => null,
        'softwareRequirements' => null,
        'softwareVersion' => null,
        'sourceOrganization' => null,
        'spatial' => null,
        'spatialCoverage' => null,
        'sponsor' => null,
        'storageRequirements' => null,
        'subjectOf' => null,
        'supportingData' => null,
        'temporal' => null,
        'temporalCoverage' => null,
        'text' => null,
        'thumbnailUrl' => null,
        'timeRequired' => null,
        'translator' => null,
        'typicalAgeRange' => null,
        'url' => null,
        'version' => null,
        'video' => null,
        'workExample' => null,
    ];
}
