<?php
declare(strict_types = 1);

namespace Brotkrueml\Schema\ViewHelper\Type;

/**
 * This file is part of the "schema" extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

/**
 * A Report generated by governmental or non-governmental organization.
 *
 * schema.org version 3.6
 */
class ReportViewHelper extends ArticleViewHelper
{
    public function initializeArguments()
    {
        parent::initializeArguments();

        $this->registerArgument('reportNumber', 'mixed', 'The number or other unique designator assigned to a Report by the publishing organization.');
    }
}
