<?php
declare(strict_types = 1);

namespace Brotkrueml\Schema\ViewHelper\Type;

/**
 * This file is part of the "schema" extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

/**
 * A service provided by an organization, e.g. delivery service, print services, etc.
 *
 * schema.org version 3.6
 */
class ServiceViewHelper extends IntangibleViewHelper
{
    public function initializeArguments()
    {
        parent::initializeArguments();

        $this->registerArgument('aggregateRating', 'mixed', 'The overall rating, based on a collection of reviews or ratings, of the item.');
        $this->registerArgument('areaServed', 'mixed', 'The geographic area where a service or offered item is provided.');
        $this->registerArgument('audience', 'mixed', 'An intended audience, i.e. a group for whom something was created.');
        $this->registerArgument('availableChannel', 'mixed', 'A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).');
        $this->registerArgument('award', 'mixed', 'An award won by or for this item.');
        $this->registerArgument('brand', 'mixed', 'The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.');
        $this->registerArgument('broker', 'mixed', 'An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.');
        $this->registerArgument('category', 'mixed', 'A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.');
        $this->registerArgument('hasOfferCatalog', 'mixed', 'Indicates an OfferCatalog listing for this Organization, Person, or Service.');
        $this->registerArgument('hoursAvailable', 'mixed', 'The hours during which this service or contact is available.');
        $this->registerArgument('isRelatedTo', 'mixed', 'A pointer to another, somehow related product (or multiple products).');
        $this->registerArgument('isSimilarTo', 'mixed', 'A pointer to another, functionally similar product (or multiple products).');
        $this->registerArgument('logo', 'mixed', 'An associated logo.');
        $this->registerArgument('offers', 'mixed', 'An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event.');
        $this->registerArgument('provider', 'mixed', 'The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.');
        $this->registerArgument('providerMobility', 'mixed', 'Indicates the mobility of a provided service (e.g. \'static\', \'dynamic\').');
        $this->registerArgument('review', 'mixed', 'A review of the item.');
        $this->registerArgument('serviceOutput', 'mixed', 'The tangible thing generated by the service, e.g. a passport, permit, etc.');
        $this->registerArgument('serviceType', 'mixed', 'The type of service being offered, e.g. veterans\' benefits, emergency relief, etc.');
        $this->registerArgument('slogan', 'mixed', 'A slogan or motto associated with the item.');
    }
}
