<?php

declare(strict_types=1);

/*
 * This file is part of the "schema" extension for TYPO3 CMS.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 */

namespace Brotkrueml\Schema\Tests\Functional\AdminPanel;

use Brotkrueml\Schema\AdminPanel\TypesInformation;
use Brotkrueml\Schema\Cache\MarkupCacheHandler;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\MockObject\Stub;
use TYPO3\CMS\Adminpanel\ModuleApi\ModuleData;
use TYPO3\CMS\Core\Localization\LanguageServiceFactory;
use TYPO3\CMS\Core\View\ViewFactoryInterface;
use TYPO3\TestingFramework\Core\Functional\FunctionalTestCase;

#[CoversClass(TypesInformation::class)]
final class TypesInformationTest extends FunctionalTestCase
{
    /**
     * @var list<string>
     */
    protected array $coreExtensionsToLoad = [
        'typo3/cms-adminpanel',
    ];

    /**
     * @var list<string>
     */
    protected array $testExtensionsToLoad = [
        'brotkrueml/schema',
    ];

    private Stub $markupCacheHandlerStub;
    private TypesInformation $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->markupCacheHandlerStub = self::createStub(MarkupCacheHandler::class);
        $this->subject = new TypesInformation($this->markupCacheHandlerStub, $this->get(ViewFactoryInterface::class));

        $this->importCSVDataSet(__DIR__ . '/../../Fixtures/be_users.csv');
        $backendUser = $this->setUpBackendUser(1);
        $GLOBALS['LANG'] = $this->get(LanguageServiceFactory::class)->createFromUserPreferences($backendUser);
    }

    protected function tearDown(): void
    {
        unset($GLOBALS['LANG']);

        parent::tearDown();
    }

    #[Test]
    public function getIdentifierReturnsIdentifierCorrectly(): void
    {
        self::assertSame('ext-schema_types', $this->subject->getIdentifier());
    }

    #[Test]
    public function getLabelReturnsLabelCorrectly(): void
    {
        self::assertSame('Types', $this->subject->getLabel());
    }

    #[Test]
    #[DataProvider('dataProviderForGetContent')]
    public function getContentWithNoCacheEntryAvailable(?string $markupFromCache, string $expected): void
    {
        $this->markupCacheHandlerStub
            ->method('getMarkup')
            ->willReturn($markupFromCache);

        $actual = $this->subject->getContent(new ModuleData());
        $actual = $this->normalizeExpectedOutput($actual);

        self::assertSame($expected, $actual);
    }

    /**
     * @return \Iterator<(array<int, null> | array<int, string>)>
     */
    public static function dataProviderForGetContent(): \Iterator
    {
        yield 'No cache entry found, assign empty array to view' => [
            null,
            <<<EXPECTED
<p>The module shows structured data on this page generated by the schema extension.</p>
<br>
<div class="typo3-adminPanel-message typo3-adminPanel-message-info">
<div class="typo3-adminPanel-message-text">
No structured data available.
</div>
</div>
EXPECTED,
        ];

        yield 'One type is available' => [
            '{"@context":"https://schema.org/","@type":"Thing","@id":"thingyId","description":"thingy description","name":"thingy name"}',
            <<<EXPECTED
<p>The module shows structured data on this page generated by the schema extension.</p>
<div class="typo3-adminPanel-form-group ext-schema-adminPanel-form-group">
<button id="ext-schema-copy" class="typo3-adminPanel-btn typo3-adminPanel-btn-primary">
<span id="ext-schema-copy-clipboard"><span title="Copy" class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-code" data-identifier="ext-schema-code" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/code.svg" width="16" height="16" alt="" />
</span>
</span></span>
<span id="ext-schema-copy-check" hidden><span title="Copied" class="t3js-icon icon icon-size-small icon-state-default icon-actions-check" data-identifier="actions-check" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-check" /></svg>
</span>
</span></span>
Copy markup
</button>
<button id="ext-schema-check-rtt" class="typo3-adminPanel-btn typo3-adminPanel-btn-primary">
<span class="t3js-icon icon icon-size-small icon-state-default icon-actions-check-badge" data-identifier="actions-check-badge" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-check-badge" /></svg>
</span>
</span>
Validate in Rich Result Test
</button>
<br><br>
<span class="t3js-icon icon icon-size-small icon-state-default icon-actions-arrow-right-alt" data-identifier="actions-arrow-right-alt" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-arrow-right-alt" /></svg>
</span>
</span>
<a class="ext-schema-adminpanel-link" href="https://validator.schema.org/" target="_blank" rel="noreferrer">Schema Markup Validator</a>
</div>
<h2 class="typo3-adminPanel-headline">
Thing
</h2>
<table class="typo3-adminPanel-table typo3-adminPanel-table-debug">
<tbody>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@type
</th>
<td>
<span class="ext-schema-adminpanel-property">Thing</span> <span class="ext-schema-adminpanel-links"><span><span class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-schema" data-identifier="ext-schema-documentation-schema" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-schema.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://schema.org/Thing" target="_blank" rel="noreferrer">Schema.org</a></span></span>
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@id
</th>
<td>
thingyId
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
description
</th>
<td>
thingy description
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
name
</th>
<td>
thingy name
</td>
</tr>
</tbody>
</table>
EXPECTED,
        ];

        yield 'Two types are available' => [
            '{"@context":"https://schema.org/","@graph":[{"@type":"Action","name":"action name","url":"http://example.org/"},{"@type":"Person","@id":"personId","name":"person name","worksFor":"someone"}]}',
            <<<EXPECTED
<p>The module shows structured data on this page generated by the schema extension.</p>
<div class="typo3-adminPanel-form-group ext-schema-adminPanel-form-group">
<button id="ext-schema-copy" class="typo3-adminPanel-btn typo3-adminPanel-btn-primary">
<span id="ext-schema-copy-clipboard"><span title="Copy" class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-code" data-identifier="ext-schema-code" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/code.svg" width="16" height="16" alt="" />
</span>
</span></span>
<span id="ext-schema-copy-check" hidden><span title="Copied" class="t3js-icon icon icon-size-small icon-state-default icon-actions-check" data-identifier="actions-check" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-check" /></svg>
</span>
</span></span>
Copy markup
</button>
<button id="ext-schema-check-rtt" class="typo3-adminPanel-btn typo3-adminPanel-btn-primary">
<span class="t3js-icon icon icon-size-small icon-state-default icon-actions-check-badge" data-identifier="actions-check-badge" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-check-badge" /></svg>
</span>
</span>
Validate in Rich Result Test
</button>
<br><br>
<span class="t3js-icon icon icon-size-small icon-state-default icon-actions-arrow-right-alt" data-identifier="actions-arrow-right-alt" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-arrow-right-alt" /></svg>
</span>
</span>
<a class="ext-schema-adminpanel-link" href="https://validator.schema.org/" target="_blank" rel="noreferrer">Schema Markup Validator</a>
</div>
<h2 class="typo3-adminPanel-headline">
Action
</h2>
<table class="typo3-adminPanel-table typo3-adminPanel-table-debug">
<tbody>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@type
</th>
<td>
<span class="ext-schema-adminpanel-property">Action</span> <span class="ext-schema-adminpanel-links"><span><span class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-schema" data-identifier="ext-schema-documentation-schema" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-schema.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://schema.org/Action" target="_blank" rel="noreferrer">Schema.org</a></span></span>
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
name
</th>
<td>
action name
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
url
</th>
<td>
<span class="ext-schema-adminpanel-property">http://example.org/</span> <span class="ext-schema-adminpanel-links"><span><span class="t3js-icon icon icon-size-small icon-state-default icon-actions-link" data-identifier="actions-link" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-link" /></svg>
</span>
</span> <a class="ext-schema-adminpanel-link" href="http://example.org/" target="_blank" rel="noreferrer">Go to website</a></span></span>
</td>
</tr>
</tbody>
</table>
<h2 class="typo3-adminPanel-headline">
Person
</h2>
<table class="typo3-adminPanel-table typo3-adminPanel-table-debug">
<tbody>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@type
</th>
<td>
<span class="ext-schema-adminpanel-property">Person</span> <span class="ext-schema-adminpanel-links"><span><span class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-schema" data-identifier="ext-schema-documentation-schema" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-schema.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://schema.org/Person" target="_blank" rel="noreferrer">Schema.org</a></span> <span><span title="Google" class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-google" data-identifier="ext-schema-documentation-google" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-google.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://developers.google.com/search/docs/appearance/structured-data/profile-page" target="_blank" rel="noreferrer">Profile page</a></span></span>
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@id
</th>
<td>
personId
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
name
</th>
<td>
person name
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
worksFor
</th>
<td>
someone
</td>
</tr>
</tbody>
</table>
EXPECTED,
        ];

        yield 'Types are sorted alphabetically' => [
            '{"@context":"https://schema.org/","@graph":[{"@type":"Thing","name":"A thing"},{"@type":"Event","name":"An event"},{"@type":"Person","name":"A person"}]}',
            <<<EXPECTED
<p>The module shows structured data on this page generated by the schema extension.</p>
<div class="typo3-adminPanel-form-group ext-schema-adminPanel-form-group">
<button id="ext-schema-copy" class="typo3-adminPanel-btn typo3-adminPanel-btn-primary">
<span id="ext-schema-copy-clipboard"><span title="Copy" class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-code" data-identifier="ext-schema-code" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/code.svg" width="16" height="16" alt="" />
</span>
</span></span>
<span id="ext-schema-copy-check" hidden><span title="Copied" class="t3js-icon icon icon-size-small icon-state-default icon-actions-check" data-identifier="actions-check" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-check" /></svg>
</span>
</span></span>
Copy markup
</button>
<button id="ext-schema-check-rtt" class="typo3-adminPanel-btn typo3-adminPanel-btn-primary">
<span class="t3js-icon icon icon-size-small icon-state-default icon-actions-check-badge" data-identifier="actions-check-badge" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-check-badge" /></svg>
</span>
</span>
Validate in Rich Result Test
</button>
<br><br>
<span class="t3js-icon icon icon-size-small icon-state-default icon-actions-arrow-right-alt" data-identifier="actions-arrow-right-alt" aria-hidden="true">
<span class="icon-markup">
<svg class="icon-color"><use xlink:href="typo3/sysext/core/Resources/Public/Icons/T3Icons/sprites/actions.svg#actions-arrow-right-alt" /></svg>
</span>
</span>
<a class="ext-schema-adminpanel-link" href="https://validator.schema.org/" target="_blank" rel="noreferrer">Schema Markup Validator</a>
</div>
<h2 class="typo3-adminPanel-headline">
Event
</h2>
<table class="typo3-adminPanel-table typo3-adminPanel-table-debug">
<tbody>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@type
</th>
<td>
<span class="ext-schema-adminpanel-property">Event</span> <span class="ext-schema-adminpanel-links"><span><span class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-schema" data-identifier="ext-schema-documentation-schema" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-schema.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://schema.org/Event" target="_blank" rel="noreferrer">Schema.org</a></span> <span><span title="Google" class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-google" data-identifier="ext-schema-documentation-google" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-google.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://developers.google.com/search/docs/appearance/structured-data/event" target="_blank" rel="noreferrer">Event</a></span></span>
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
name
</th>
<td>
An event
</td>
</tr>
</tbody>
</table>
<h2 class="typo3-adminPanel-headline">
Person
</h2>
<table class="typo3-adminPanel-table typo3-adminPanel-table-debug">
<tbody>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@type
</th>
<td>
<span class="ext-schema-adminpanel-property">Person</span> <span class="ext-schema-adminpanel-links"><span><span class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-schema" data-identifier="ext-schema-documentation-schema" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-schema.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://schema.org/Person" target="_blank" rel="noreferrer">Schema.org</a></span> <span><span title="Google" class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-google" data-identifier="ext-schema-documentation-google" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-google.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://developers.google.com/search/docs/appearance/structured-data/profile-page" target="_blank" rel="noreferrer">Profile page</a></span></span>
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
name
</th>
<td>
A person
</td>
</tr>
</tbody>
</table>
<h2 class="typo3-adminPanel-headline">
Thing
</h2>
<table class="typo3-adminPanel-table typo3-adminPanel-table-debug">
<tbody>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
@type
</th>
<td>
<span class="ext-schema-adminpanel-property">Thing</span> <span class="ext-schema-adminpanel-links"><span><span class="t3js-icon icon icon-size-small icon-state-default icon-ext-schema-documentation-schema" data-identifier="ext-schema-documentation-schema" aria-hidden="true">
<span class="icon-markup">
<img src="typo3conf/ext/schema/Resources/Public/Icons/documentation-schema.svg" width="16" height="16" alt="" />
</span>
</span> <a class="ext-schema-adminpanel-link" href="https://schema.org/Thing" target="_blank" rel="noreferrer">Schema.org</a></span></span>
</td>
</tr>
<tr>
<th scope="row" class="typo3-adminPanel-table-cell-key">
name
</th>
<td>
A thing
</td>
</tr>
</tbody>
</table>
EXPECTED,
        ];
    }

    private function normalizeExpectedOutput(string $output): string
    {
        $lines = \explode("\n", $output);
        $result = [];
        foreach ($lines as $line) {
            $line = \trim($line);
            if ($line === '') {
                continue;
            }
            if (\str_starts_with($line, '<link rel')) {
                continue;
            }
            $result[] = $line;
        }

        return \implode("\n", $result);
    }
}
