name: Documentation

permissions: {}

on:
  push:
    paths:
      - 'Documentation/**'
  pull_request:
    paths:
      - 'Documentation/**'


jobs:
  tests:
    name: Rendering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Documentation renders without warnings
        run: |
          docker run --rm --pull always -v $(pwd):/project \
             ghcr.io/typo3-documentation/render-guides:latest --config=Documentation --no-progress --fail-on-log
