name: Documentation

permissions: {}

on:
  push:
    paths:
      - 'Documentation/**'
  pull_request:
    paths:
      - 'Documentation/**'


jobs:
  tests:
    name: Rendering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Documentation renders without warnings
        run: |
          docker run --rm --pull always -v $(pwd):/project \
             ghcr.io/typo3-documentation/render-guides:latest --config=Documentation --no-progress --fail-on-log
